# -*- coding: utf-8 -*-
"""normaldistributionpynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yLkEuWh7PmRdqSNnjoE9qiceGsflqEMS
"""

import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

beml_df=pd.read_csv("/content/BEML.csv")

beml_df

glaxo_df=pd.read_csv("/content/GLAXO.csv")
glaxo_df

beml_df=beml_df[["Date","Close"]]
glaxo_df=glaxo_df[["Date","Close"]]

beml_df

glaxo_df

beml_df.dtypes

glaxo_df.dtypes

glaxo_df=glaxo_df.set_index(pd.DatetimeIndex(glaxo_df["Date"]))

beml_df=beml_df.set_index(pd.DatetimeIndex(beml_df["Date"]))

glaxo_df

beml_df

import matplotlib.pyplot as plt
import seaborn as sn
plt.plot(glaxo_df.Close,color="pink")
plt.xlabel("Time",color="red")
plt.ylabel("Close Price",color="green")

plt.plot(beml_df.Close,color="green")
plt.xlabel("Time",color="Chocolate")
plt.ylabel("Close Price",color="purple")

glaxo_df["gain"]=glaxo_df.Close.pct_change(periods=1)

glaxo_df

beml_df["gain"]=beml_df.Close.pct_change(periods=1)
beml_df

glaxo_df=glaxo_df.dropna()
beml_df=beml_df.dropna()

glaxo_df

beml_df

plt.figure(figsize=(8,5))
plt.plot(glaxo_df.gain,color="Violet")
plt.xlabel("Time",color="Orange")
plt.ylabel("gain",color="Olive")

plt.figure(figsize=(8,5))
plt.plot(beml_df.gain)
plt.xlabel("Time")
plt.ylabel("gain")

plt.figure(figsize=(10,5))
plt.suptitle("Distribution",fontsize="15")
plt.subplot(1, 2, 1)
sn.distplot(glaxo_df.gain,label="Glaxo")
plt.xlabel("gain",color="red")
plt.ylabel("density",color="pink")
plt.legend()
plt.figure(figsize=(10,5))
plt.suptitle("Distribution",fontsize="15")
plt.subplot(1, 2, 2)
sn.distplot(beml_df.gain,label="Beml")
plt.xlabel("gain",color="red")
plt.ylabel("density",color="pink")
plt.legend()

plt.figure(figsize=(10,5))
sn.distplot(beml_df.gain,label="BEML")
sn.distplot(glaxo_df.gain,label="GLAXO")
plt.xlabel("gain")
plt.ylabel("density")
plt.legend()

print("mean:",round(glaxo_df.gain.mean(),4))
print("standard devision:",round(glaxo_df.gain.std(),4))

print("mean:",round(beml_df.gain.mean(),4))
print("standard devision:",round(beml_df.gain.std(),4))

from scipy import stats
stats.norm.cdf(-0.02,0.0004,0.0134)

stats.norm.cdf(-0.02,0.0003,0.0264)

1-stats.norm.cdf(0.02,0.0004,0.0134)

stats.norm.cdf(-.02,
 loc=beml_df.gain.mean(),
  scale=beml_df.gain.std())

